apiVersion: v1
kind: Service
metadata:
  name: portfolio-go-app
  labels:
    app: portfolio-go-app
spec:
  selector:
    app: portfolio-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP